Repository COS301-SE-2024/MyCity, pull requests merged in 2024-08, with the labels that each got.

#375 PR to have changes in dev for new branch
  backend/tests/integration/searching_integration_test.py
  backend/tests/integration/tenders_integration_test.py
  backend/tests/integration/tickets_integration_test.py
  backend/tests/unit/tenders_unit_test.py
  backend/tests/unit/tickets_unit_test.py
  frontend/package.json
  frontend/src/app/notifications/citizen/page.tsx
  frontend/src/components/Notifications/NotificationPromt.tsx
Labels: bug, testing

#378 used overrides option in package.json to fix vulnerability
  backend/requirements.txt
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#407 added endpoint to retrieve geodata for all unclosed tickets
  backend/chalicelib/tickets/tickets_controllers.py
  backend/chalicelib/tickets/tickets_routes.py
Labels: backend

#413 Tenders Tests and README changes
  README.md
  backend/chalicelib/tenders/tenders_controllers.py
  backend/chalicelib/tenders/tenders_routes.py
  backend/chalicelib/upvotes/upvotes_controllers.py
  backend/chalicelib/upvotes/upvotes_routes.py
  backend/requirements.txt
  backend/tests/integration/tenders_integration_test.py
  backend/tests/unit/tenders_unit_test.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/dashboard/citizen/page.tsx
  frontend/src/app/dashboard/municipality/page.tsx
  frontend/src/app/notifications/citizen/page.tsx
  frontend/src/components/FaultCardContainer/DashboardFualtCardContainer.tsx
  frontend/src/components/FaultCardUserView/DashboardFaultCardUserView.tsx
  frontend/src/components/FaultTable/FaultTable.tsx
  frontend/src/components/RecordsTable/IntegratedRecord.tsx
  frontend/src/components/RecordsTable/IntegratedRecordsTable.tsx
  frontend/src/components/RecordsTable/MuniTenders.tsx
  frontend/src/components/Signup/MunicipalitySignup.tsx
  frontend/src/components/Tenders/MuniTenderMax.tsx
  frontend/src/components/Tenders/MuniTenderMini.tsx
  frontend/src/components/TicketViewMuni/TicketViewMuni.tsx
  frontend/src/context/UserProfileContext.tsx
  frontend/src/services/tender.service.ts
  frontend/src/services/tickets.service.ts
Labels: documentation, testing

#441 added multipart_handler.py file to handle form-data and file uploads to s3
  backend/chalicelib/multipart_handler.py
  backend/requirements.txt
Labels: backend

#470 All users search pages
  backend/chalicelib/multipart_handler.py
  backend/chalicelib/tenders/tenders_controllers.py
  backend/chalicelib/watchlist/watchlist_controllers.py
  backend/chalicelib/watchlist/watchlist_routes.py
  backend/requirements.txt
  frontend/package-lock.json
  frontend/src/app/dashboard/municipality/page.tsx
  frontend/src/app/search/citizen/page.tsx
  frontend/src/app/search/municipality/page.tsx
  frontend/src/app/search/service-provider/page.tsx
  frontend/src/components/FaultTable/FaultTable.tsx
  frontend/src/components/RecordsTable/IntegratedRecord.tsx
  frontend/src/components/RecordsTable/IntegratedRecordsTable.tsx
  frontend/src/components/Settings/company/ChangeCompanyInfo.tsx
  frontend/src/components/Settings/company/ChangeCompanyPass.tsx
  frontend/src/components/Settings/company/CompanyCode.tsx
  frontend/src/components/StatusCardContainer/DashboardStatusCardContainer.tsx
  frontend/src/components/StatusCardContainer/StatusCardContainer.tsx
  frontend/src/components/StatusCardUser/DashboardStatusCardUser.tsx
  frontend/src/components/StatusCardUser/StatusCardUser.tsx
  frontend/src/components/StatusCardUserView/DashboardStatusCardUserView.tsx
  frontend/src/components/StatusCardUserView/StatusCardUserView.tsx
  frontend/src/components/Tenders/TendersTemplate.tsx
  frontend/src/components/TicketViewMuni/TicketViewMuni.tsx
  frontend/src/context/MapboxMap.tsx
  frontend/src/hooks/mapboxmap.ts
  frontend/src/hooks/useMapbox.ts
  frontend/src/services/search.service.ts
  frontend/src/services/tender.service.ts
  frontend/src/services/tickets.service.ts
Labels: bug

#490 added endpoint for uploading user profile picture
  .github/workflows/deploy.yml
  backend/.chalice/update_api_gateway.py
  backend/app.py
  backend/chalicelib/users/__init__.py
  backend/chalicelib/users/users_controllers.py
  backend/chalicelib/users/users_routes.py
Labels: backend

#519 Comments
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Comments/comment.tsx
  frontend/src/components/Comments/comments.tsx
  frontend/src/components/FaultCardUserView/FaultCardUserView.tsx
Labels: enhancement

#522 Comments
  frontend/src/services/tickets.service.ts
Labels: bug

#528 Viewing of comments
  frontend/src/components/Comments/comments.tsx
  frontend/src/components/FaultCardContainer/DashboardFualtCardContainer.tsx
  frontend/src/components/FaultCardUser/FaultCardUser.tsx
  frontend/src/components/FaultCardUserView/FaultCardUserView.tsx
  frontend/src/components/NotificationsCitizenNew/TicketNoti.tsx
  frontend/src/components/StatusCardContainer/StatusCardContainer.tsx
  frontend/src/services/tickets.service.ts
  package-lock.json
Labels: bug

#564 updated view_ticket_data function to work with deep links
  .github/workflows/deploy.yml
  backend/chalicelib/tickets/tickets_controllers.py
  frontend/.gitignore
  frontend/public/sw.js
  frontend/public/swe-worker-5c72df51bb1f6ee0.js
  frontend/public/workbox-c2c0676f.js
Labels: backend

#656 bump micromatch from 4.0.7 to 4.0.8 in /frontend
  frontend/package-lock.json
Labels: dependencies
